config/routes.rb
Rails.application.routes.draw do	

  get '/login' => 'admin/sessions#new'
  get '/logout' => 'admin/sessions#destroy'

	namespace :admin do
  resources :blogs
  resources :posts
  resources :settings, only: [:new, :create, :edit, :update]
  resources :dashboard, only: [:index]
  resources :notifications, only: [:index, :destroy]
  resources :messages, only: [:index, :show, :update, :destroy]
  resources :visitors, only: [:index, :destroy]
  resources :comments, only: [:index, :update, :destroy]
  resources :tags, except: [:index]
	resources :sessions, only: [:new, :create, :destroy]
	resources :moderators, only: [:index, :edit, :update]
	end

  resources :posts, only: [:index, :show]
  resources :messages, only: [:new, :create]
  resources :comments, only: [:create]
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, dependent: :destroy
  belongs_to :visitor
  has_many :notificaions, as: :notifiable

  validates :message, presence: true

  scope :approved, -> { where status: true }

	def self.matching_fullname_or_message params
		joins(:visitor).where("fullname LIKE ? OR message LIKE ?", "%#{params}%", "%#{params}%") 
	end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :visitor

  validates :content, presence: true

  def self.matching_fullname_or_content params
  	joins(:visitor).where("fullname LIKE ? OR content LIKE ?", "%#{params}%","%#{params}%")
  end
end

app/models/moderator.rb
class Moderator < ApplicationRecord
	has_secure_password

	has_many :post

	validates :fullname, presence: true
	validates :username, presence: true, format: {with: /@/, message: "is not valid"}
	validates :password, presence: true
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :notifiable, polymorphic: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags
  has_many :comments, dependent: :destroy
  belongs_to :moderator

  validates :title, presence: true
  validates :content, presence: true

  scope :published, -> { where(publish: true).order(id: :desc) }

  def self.matching_title_or_content search
  	where("title LIKE ? OR content LIKE ?", "%#{search}%", "%#{search}%")
  end

  def self.filter_by_tags param_tag
  	includes(:tags).where(publish: true, tags:{name: param_tag}).order(id: :desc)
  end
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/setting.rb
class Setting < ApplicationRecord
	def self.site_name
		Setting.first.try(:site_name)
	end

	def self.post_per_page
		Setting.first.try(:post_per_page)
	end

	def self.tag_visibile?
		Setting.first.try(:tag_visibility)
	end
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :posts, through: :post_tags

	validates :name, presence: true

	def in_use?
		PostTag.exists?(tag_id: self.id)		
	end
end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
	has_many :notifications, as: :notifiable
	has_many :messages, dependent: :destroy
	has_many :comments, dependent: :destroy

	validates :fullname, presence: true
	validates :email, format: { with: /@/, message: "is not valid"}

	accepts_nested_attributes_for :comments
	accepts_nested_attributes_for :messages

	after_save :notify
	def notify
		notifications.build.save
	end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::ApplicationController
  def index
		@posts = Post.last 5 
		@comments = Comment.last 5
		@visitors = Visitor.last 5
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Prevent CSRF attacks by raising an expection.
	# # For API's, you may want to use :null_session instead.
	protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
		if visitor.save
			flash[:notice] = "successfully Created New Comment"
		else
			flash[:notice] = "There was a problem creating your comment"
			set_visitor_sessions
		end

  	redirect_to posts_path
  end

  private

  def visitor_comments_params
  	params.require(:visitor).permit(:fullname, :email, :comments_attributes => [:message, :post_id])
	end
 
	def visitor
		@visitor ||= VisitorCommentService.new(visitor_comments_params).visitor
	end

	def set_visitor_sessions
		session[:visitor_errors] = visitor.errors.full_messages
		session[:visitor_params] = visitor_comments_params
	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
  	@visitor_message = Visitor.new(messages: [Message.new])
  end

  def create
  	if visitor.save
			flash[:notice] = "successfully sent your message"
			redirect_to new_message_path
		else
			@visitor_message = visitor
			render :new
		end
  end


  private

  def strong_params 
  	params.require(:visitor).permit(:fullname, :email, messages_attributes: [:content])
  end

  def visitor
  	@visitor ||= VisitorMessageService.new(strong_params).visitor
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	after_action :clear_sessions, only: [:show]
	
  def index
  	if params[:tag]
  	@posts = Post.filter_by_tags(params[:tag]).page(params[:page]).per(Setting.post_per_page)
  	else
			@posts = Post.published.page(params[:page]).per(Setting.post_per_page)
  	end
  end

	  def show
	  	@post = Post.find(params[:id])
	  	@visitor_comments = visitor_comments
	  end


	  def clear_sessions
	  	[:visitor_errors, :visitor_params].each { |k| session.delete(k) }
	  end

	  def visitor_comments
	  	if session[:visitor_errors]
	  		VisitorCommentService.new(session[:visitor_params]).visitor
	  	else
	  		Visitor.new(comments: [Comment.new])
	  	end
	  end
	end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	
	def	status_converter(status, truthy: nil, falsey: nil)
		if status 
			truthy
		else
			falsey
		end
	end

	def time_ago time
		"#{time_ago_in_words(time)} ago"
	end
	
	def double_digit_number n
	'%02d' % n
	
	end
end

app/helpers/bucket_helper.rb
module BucketHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/dashboard/index.html.erb
<h1>Dashboard</h1>

<h2>Post</h2>
<%= link_to "Create New Post", new_admin_post_path %><br>
<%= link_to "List Posts", admin_posts_path %>


	<table class ="table table-bordered table-hover">
		<thead>
			<tr>
				<td><b>Title</td>
				<td><b>Replies</td>
				<td><b>Dates</td>
				<td><b>Actions</td>
			</tr>
		</thead>
		<tbody>

			<% @posts.each do |post| %>
				<tr>
					<td><%= truncate(post.title, length:40, seperator:"") %></td>
					<td><%= post.comments.count %></td>
					<td><%= time_ago(post.created_at) %></td>
					<td>
						<%= link_to "Edit", edit_admin_post_path(post) %>|
						<%= link_to "View", admin_posts_path(post) %>|
						<%= link_to "Del", admin_post_path(post), method: :delete, data:{confirm:"are you sure?"} %>|
					</td>
				</tr>
			<% end -%>
		</tbody>
	</table>


	<h2>Comments</h2>

	<%= link_to "List All Comments", admin_comments_path %>

	<% @comments.each do |comment| %>
		<td><p><%= comment.visitor.fullname %></p></td>
		<td><p><%= truncate(comment.message, length:120, seperator:"") %></p></td>
		<td><p><%= time_ago(comment.created_at) %></p></td>
		<hr>
	<% end -%>

	<h2>Visitors</h2>
	<table class ="table table-bordered table-hover">
		<thead>
			<tr>
				<th>#</th>
				<th>Fullname</th>
				<th>Email</th>
				<th>Created</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>

			<% @visitors.each_with_index do |visitor, index| %>
				<tr>
					<td><%= index + 1 %></td>
					<td><%= visitor.fullname %></td>
					<td><%= visitor.email %></td>
					<td><%= time_ago(visitor.created_at) %></td>
					<td>
						<%= link_to "Deleted", admin_visitors_path(visitor), method: :delete, data:{confirm:"are you sure?"} %>
					</td>
				</tr>
			<% end -%>
		</tbody>
	</table>